version: '3'

services:
    cron:
        build:
            context: .
            dockerfile: Dockerfile
        image: jwansek/yaoi-communism
        network_mode: host
        volumes:
          - ./yc.log:/app/yc.log
          - ./posted_images.csv:/app/posted_images.csv
