version: '3'

services:
    cron:
        container_name: yaoi-communism
        build:
            context: .
            dockerfile: Dockerfile
        image: reg.reaweb.uk/yaoi-communism
        network_mode: host
        volumes:
          - ./config.json:/app/config.json
          - ./yc.log:/app/yc.log
          - ./posted_images.csv:/app/posted_images.csv
